services:
  backend:
    image: glaxer/poc-back-online:latest
    hostname: backend
    container_name: backend
    expose:
      - "1313"  # API backend
      - "1414"  # WebSocket
    networks:
      - app-network

  frontend:
    image: glaxer/poc-front-online:latest
    container_name: frontend
    expose:
      - "1212"  # Frontend
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"     # HTTP 
      - "443:443"   # HTTPS 
    volumes:
      - ./nginx_proxy.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
